import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Playfair,
  Open_Sans,
  Poppins,
} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import { ThemeProvider } from "next-themes";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";

const openSans = Open_Sans({
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en" suppressHydrationWarning>
        <body className={`${openSans.variable} antialiased`}>
          <ThemeProvider
            attribute="class"
            disableTransitionOnChange
            defaultTheme="system"
            enableSystem
          >
            <Navbar />
            <main className="my-4">{children}</main>
          </ThemeProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
